import { Menu } from "./components/Menu";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="bg-onyx flex">
          <Menu />
          <div className="ml-24 md:ml-64">{children}</div>
        </div>
      </body>
    </html>
  );
}
